releases: 
- name: release-2
  chart: ./my-helmchart
  values:
  - ./my-helmchart/capp-values.yaml
  set: 
  - name: deploy_to_prod.create
    value: true 
  - name: deployment.image.tag
    value: {{ .Values.deployment.image.tag }}
